logging:
  level:
    org.springframework.web: DEBUG

spring:
#    web:
#      resources:
#        static-locations: classpath:/static/

    datasource:
      url: jdbc:mysql://localhost:3306/web_novel_service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      username: root
      password: tmd8246!

    jpa:
      show-sql: true
      hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 125342375854-7nqednq5hb72tib83p55uldu04cbm635.apps.googleusercontent.com
              clientSecret: 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
              scope:
                - email
                - profile
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
